# Generated by Django 5.2.14 on 2026-05-12 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_location_label', models.CharField(max_length=255)),
                ('current_location_lat', models.FloatField()),
                ('current_location_lon', models.FloatField()),
                ('pickup_location_label', models.CharField(max_length=255)),
                ('pickup_location_lat', models.FloatField()),
                ('pickup_location_lon', models.FloatField()),
                ('dropoff_location_label', models.CharField(max_length=255)),
                ('dropoff_location_lat', models.FloatField()),
                ('dropoff_location_lon', models.FloatField()),
                ('current_cycle_hours', models.FloatField(help_text='Hours already used in the rolling 70-hour / 8-day cycle.')),
                ('departure_at', models.DateTimeField(help_text='Local-time clock the planner started from.')),
                ('total_distance_miles', models.FloatField(default=0)),
                ('total_drive_minutes', models.IntegerField(default=0)),
                ('total_on_duty_minutes', models.IntegerField(default=0)),
                ('total_off_duty_minutes', models.IntegerField(default=0)),
                ('total_sleeper_minutes', models.IntegerField(default=0)),
                ('total_trip_minutes', models.IntegerField(default=0)),
                ('number_of_days', models.IntegerField(default=1)),
                ('plan_payload', models.JSONField()),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
